from pathlib import Path
import base64
from datetime import datetime,timedelta,timezone
from cryptography import x509
from cryptography.x509.oid import NameOID
from cryptography.hazmat.primitives import hashes,serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives.serialization import pkcs7
# Deliberately synthetic, generated from this literal text; contains no user documents.
stream=b'BT /F1 24 Tf 48 730 Td (P7M GRATIS - TEST PDF) Tj 0 -40 Td /F1 12 Tf (Documento sintetico senza dati personali.) Tj ET'
objects=[b'<< /Type /Catalog /Pages 2 0 R >>',b'<< /Type /Pages /Kids [3 0 R] /Count 1 >>',b'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',b'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',b'<< /Length '+str(len(stream)).encode()+b' >>\nstream\n'+stream+b'\nendstream']
pdf=b'%PDF-1.4\n';offsets=[]
for index,obj in enumerate(objects,1):
 offsets.append(len(pdf));pdf+=str(index).encode()+b' 0 obj\n'+obj+b'\nendobj\n'
xref=len(pdf);pdf+=b'xref\n0 6\n0000000000 65535 f \n'+b''.join(f'{offset:010d} 00000 n \n'.encode() for offset in offsets)+b'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+str(xref).encode()+b'\n%%EOF\n'
key=rsa.generate_private_key(public_exponent=65537,key_size=2048)
now=datetime.now(timezone.utc);name=x509.Name([x509.NameAttribute(NameOID.COMMON_NAME,'Synthetic PDF Test')])
cert=x509.CertificateBuilder().subject_name(name).issuer_name(name).public_key(key.public_key()).serial_number(7001).not_valid_before(now-timedelta(days=1)).not_valid_after(now+timedelta(days=3650)).sign(key,hashes.SHA256())
busta=pkcs7.PKCS7SignatureBuilder().set_data(pdf).add_signer(cert,key,hashes.SHA256()).sign(serialization.Encoding.DER,[pkcs7.PKCS7Options.Binary])
Path('test/fixtures/synthetic_pdf.p7m').write_bytes(busta)
text=Path('test/fixtures/valid.p7m').read_bytes()
Path('integration_test/fixtures.dart').write_text('// Synthetic test fixtures only. PDF literal content generated by tool/generate_synthetic_pdf.py.\n'+ '\n'.join('const '+label+' = '+repr(base64.b64encode(data).decode())+';' for label,data in [('textP7m',text),('pdfP7m',busta)]))
print('Generated synthetic PDF fixture: P7M GRATIS - TEST PDF / Documento sintetico senza dati personali.')
